### ISSUE TITLE
JSON and SysML File

### ISSUE THREAD

**Issue by ReisKoenig97** [Systems-Modeling/SysML-v2-API-Services#120]
Hello everybody,

I'm fairly new to SysMLv2 and was testing the local API via Docker, Running a small python script to connect the data. Now I have some general questions about the .json and .sysml file since the REST API uses the standard .json file for responses. 

1) For example I'm modeling my sysmlv2 model inside jupyter (for better visualizations) this is saved and used as a .sysml file which based on json but its not quite the same obviously. The question is how can I transfer my .sysml file to the (local) Server. And the same way around. How can I translate my model which is on the local server when I`m only getting the JSON as response and I need a .sysml File to represent it inside Jupyter. Are there other tools to visualize the json formatted model? 

2) When testing the REST API and creating (and posting) a new model via JSON format. It appears that no matter which id, name, description I write, on the Server it generates the id (which I think is intended) by its own, but name and description is "null"

![{3813B1FE-D981-430E-AA76-CE020F7A2817}](https://github.com/user-attachments/assets/cdfeaf82-5bed-41bf-83f9-e69b355e3901)
That gives me:
![{FF7C2649-9830-4AB4-BFF1-063B678A35F2}](https://github.com/user-attachments/assets/f86f53ff-2d94-4d3d-ab49-9438fd54e91f)

Hope somebody can answer my questions. Thanks in advance

**Comment by seidewitz** [comment]
Please only submit issues on GitHub that report reproducable bugs with the implementation. If you would like help understanding the standard or using the implementations, please join the Google Group at https://groups.google.com/g/sysml-v2-release and start a discussion there.

Thanks.
