### ISSUE TITLE
question: POST for elements

### ISSUE THREAD

**Issue by JuanQuinGom** [Systems-Modeling/SysML-v2-API-Services#66]
Hello, is there an option to use a POST request to add elements to a specific commit? Thanks for your attention

**Comment by manasbajaj** [comment]
Hello @JuanQuinGom - Please see the new repository SysML-v2-API-Cookbook. 

https://github.com/Systems-Modeling/SysML-v2-API-Cookbook

The Project_Commit_Branch_Tag_Recipe.ipynb has an example to create successive commits with new elements.

https://github.com/Systems-Modeling/SysML-v2-API-Cookbook/blob/main/Project_Commit_Branch_Tag_Recipe.ipynb
