### ISSUE TITLE
Project `PUT` method does not work.

### ISSUE THREAD

**Issue by csanadtelbisz** [Systems-Modeling/SysML-v2-API-Services#72]
**SysML v2 API and Services version:** 2022-06 (on Jul 18, 2022)

**Steps to reproduce:**
- Using the api client, create a project.
- Modify the name/description of the project with the project `PUT` method.
- Get the project details. The returned value of the properties name and description are null.

The following simple Kotlin snippet reproduces the problem: [api-client-bug-report.zip](https://github.com/Systems-Modeling/SysML-v2-API-Services/files/9190196/api-client-bug-report.zip) (the project uses the [SysML v2 API Java Client](https://github.com/Systems-Modeling/SysML-v2-API-Java-Client). Essential part:

```kotlin
val projectApi = ProjectApi(defaultClient)
//...
val project = projectApi.postProject(Project().apply { name = "demo project" })
val MODIFIED_NAME = "modified name"
projectApi.putProjectById(project.atId, project.apply { name = MODIFIED_NAME })
val modifiedProject = projectApi.getProjectById(project.atId)
assert(modifiedProject.name == MODIFIED_NAME) // false: AssertionError (if -ea flag is provided for JVM), modifiedProject.name = null
```

**Expected output:** the project name/description is the updated name/description

**Actual output:** these properties are null

**Comment by manasbajaj** [comment]
Hello @csanadtelbisz - We have recorded this issue in the internal development. This will be resolved in the 2022-08 or 2022-09 release.

We also want to point you to the new repository for example Jupyter notebooks with API calls.

https://github.com/Systems-Modeling/SysML-v2-API-Cookbook
